import { useRef, useState } from 'react'
import { Activity, ArrowLeft, ArrowRight, BookOpen, Brain, Check, ChevronDown, ChevronUp, CircleHelp, FileText, GraduationCap, Lightbulb, LoaderCircle, Menu, RotateCcw, Sparkles, Target, Upload, X } from 'lucide-react'
import { analyzeFile, evaluateQuiz } from './services/api'

const sampleText = `Introduction to Artificial Intelligence\n\nArtificial intelligence (AI) is the field of computer science that creates systems able to perform tasks that usually require human intelligence. These tasks include recognizing speech, understanding language, solving problems and making decisions.\n\nMachine learning is a branch of AI in which computers learn patterns from data rather than following only explicitly programmed rules. In supervised learning, a model learns from labeled examples. In unsupervised learning, it looks for patterns in unlabeled data. Reinforcement learning trains an agent to make decisions by receiving rewards or penalties for its actions.\n\nA neural network is a computing system inspired by networks of neurons. Deep learning uses neural networks with many layers to learn complex patterns. Training data is used to fit a model, while test data helps estimate how well it generalizes to new examples.\n\nNatural language processing (NLP) helps computers work with human language. Computer vision enables systems to interpret images and video. AI applications include medical image analysis, recommendation systems, translation and voice assistants.\n\nAI systems can reproduce biases present in training data. Privacy, transparency, safety and human oversight are important considerations when designing responsible AI. AI can support human decision-making, but its output should be checked in high-stakes situations.`

const features = [{ icon: Sparkles, title: 'Clear summaries', text: 'Get the big ideas and key points without losing the detail.' }, { icon: Brain, title: 'Topic discovery', text: 'See the concepts your material spends time explaining.' }, { icon: CircleHelp, title: 'Practice questions', text: 'Turn the reading into questions you can actually use.' }, { icon: Target, title: 'Know what to revisit', text: 'See your score and the topics behind missed answers.' }]

export default function App() {
  const [page, setPage] = useState('home'), [analysis, setAnalysis] = useState(null), [file, setFile] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState(''), [result, setResult] = useState(null), [answers, setAnswers] = useState({}), [index, setIndex] = useState(0), [expanded, setExpanded] = useState(-1), [dragging, setDragging] = useState(false)
  const inputRef = useRef(null)
  const selectFile = f => { setError(''); if (!f) return false; if (!/\.(pdf|txt)$/i.test(f.name)) { setFile(null); setError('Choose a PDF or TXT file.'); return false } if (f.size > 10 * 1024 * 1024) { setFile(null); setError('The file must be 10 MB or smaller.'); return false } setFile(f); return true }
  const runAnalysis = async selected => { const chosen = selected || file; if (!chosen) { setError('Choose a study document to get started.'); return } setBusy(true); setError(''); try { const data = await analyzeFile(chosen); setAnalysis(data); setFile(chosen); setPage('analysis') } catch (e) { setError(e.message) } finally { setBusy(false) } }
  const handleFile = f => { if (selectFile(f)) runAnalysis(f) }
  const startQuiz = () => { setAnswers({}); setIndex(0); setResult(null); setError(''); setPage('quiz') }
  const submitQuiz = async () => { if (!analysis) return; if (!Object.keys(answers).length) { setError('Choose at least one answer before submitting.'); return } setBusy(true); setError(''); try { setResult(await evaluateQuiz(analysis, answers)); setPage('results') } catch (e) { setError(e.message) } finally { setBusy(false) } }
  const reset = () => { setAnalysis(null); setFile(null); setResult(null); setAnswers({}); setError(''); setPage('dashboard') }
  const nav = [{ id: 'dashboard', label: 'Workspace', icon: BookOpen }, ...(analysis ? [{ id: 'analysis', label: 'My analysis', icon: Activity }, { id: 'questions', label: 'Study questions', icon: CircleHelp }] : [])]

  return <div className="app-shell">
    <aside className="sidebar"><button className="brand" onClick={() => setPage('home')}><span className="brand-mark"><GraduationCap size={21}/></span><span>study<span className="brand-accent">mate</span><small>YOUR AI STUDY SPACE</small></span></button><div className="nav-label">MENU</div>{nav.map(item => <button key={item.id} onClick={() => setPage(item.id)} className={`nav-item ${page === item.id ? 'active' : ''}`}><item.icon size={17}/>{item.label}</button>)}<div className="side-bottom"><div className="side-tip"><Lightbulb size={17}/><strong>A small study habit</strong><span>Try a quick quiz after each reading session.</span></div><span className="version">AI LAB PROJECT · LOCAL DEMO</span></div></aside>
    <main className="main-area"><header className="topbar"><div className="crumb"><span>Workspace</span><span className="slash">/</span><strong>{({home:'Overview',dashboard:'My materials',analysis:'Analysis',questions:'Study questions',quiz:'Quiz',results:'Results'})[page]}</strong></div><div className="top-actions"><span className="status-dot"/> <span className="status-text">Study session</span><span className="avatar">S</span></div></header>
      {page === 'home' && <section className="welcome page-pad"><div className="eyebrow"><span className="eyebrow-icon"><Sparkles size={13}/></span> YOUR PERSONAL STUDY ASSISTANT</div><h1>Learn smarter.<br/><span>Prepare better.</span></h1><p className="hero-copy">Turn your course material into a focused learning session. Clear notes, useful questions, and a little more confidence before the exam.</p><div className="hero-actions"><button className="button primary" onClick={() => setPage('dashboard')}>Open my workspace <ArrowRight size={16}/></button><button className="button quiet" onClick={() => document.getElementById('how-it-works')?.scrollIntoView({ behavior: 'smooth' })}>How it works <ArrowRight size={15}/></button></div><div className="hero-proof"><div className="proof-icon"><Brain size={19}/></div><span><b>Built around your material</b><small>Study tools grounded in the notes you provide.</small></span><span className="proof-tag">STUDY, WITH INTENTION</span></div><div className="section-heading"><div><span className="overline">A BETTER WAY TO REVIEW</span><h2>Everything you need to get unstuck.</h2></div><span className="muted">A little structure goes a long way.</span></div><div className="feature-grid">{features.map(({icon:Icon,title,text}, i) => <article className="feature-card" key={title}><span className={`feature-icon hue-${i}`}><Icon size={18}/></span><h3>{title}</h3><p>{text}</p></article>)}</div><div className="how-strip" id="how-it-works"><span className="overline">HOW IT WORKS</span><div className="steps"><span><i>01</i> Add your notes</span><ArrowRight size={16}/><span><i>02</i> Review the analysis</span><ArrowRight size={16}/><span><i>03</i> Practice and improve</span></div></div></section>}


      {page === 'dashboard' && <section className="page-pad">
        <div className="page-title-row">
          <div><div className="eyebrow">YOUR STUDY SPACE</div><h1 className="page-title">Study workspace</h1><p className="muted">Choose a PDF or TXT file. Analysis starts automatically.</p></div>
          <div className="date-pill"><span className="status-dot"/> Ready</div>
        </div>
        <div className="stats-row">
          <div className="stat-card"><span className="stat-label">MATERIALS</span><b>{analysis ? '01' : '00'}</b><small>{analysis ? 'Latest analysis' : 'None yet'}</small></div>
          <div className="stat-card"><span className="stat-label">TOPICS</span><b>{analysis?.topics?.length || '—'}</b><small>{analysis ? 'From this file' : 'After upload'}</small></div>
          <div className="stat-card"><span className="stat-label">QUIZ QUESTIONS</span><b>{analysis?.mcqs?.length || '—'}</b><small>{analysis ? 'Ready' : 'After upload'}</small></div>
          <div className="stat-card"><span className="stat-label">LAST SCORE</span><b>{result ? `${result.percentage}%` : '—'}</b><small>{result ? result.performance : 'No quiz yet'}</small></div>
        </div>
        <div className="workspace-grid">
          <div className="upload-panel">
            <div className="panel-head"><div><span className="overline">NEW ANALYSIS</span><h2>Upload a PDF or TXT file</h2><p className="muted">File content is sent to OpenRouter for analysis. This app does not save your file.</p></div><span className="panel-icon"><Upload size={20}/></span></div>
            <div className={`dropzone ${dragging ? 'dragging' : ''}`} onDragOver={e => {e.preventDefault();setDragging(true)}} onDragLeave={() => setDragging(false)} onDrop={e => {e.preventDefault();setDragging(false);handleFile(e.dataTransfer.files[0])}} onClick={() => inputRef.current?.click()} role="button" tabIndex="0" onKeyDown={e => e.key === 'Enter' && inputRef.current?.click()}>
              <input ref={inputRef} type="file" accept=".pdf,.txt,application/pdf,text/plain" hidden onChange={e => {handleFile(e.target.files?.[0]);e.target.value = ''}}/>
              <span className="upload-icon"><Upload size={21}/></span><b>{file ? file.name : 'Choose or drop a study file'}</b><span>{busy ? 'Analyzing your file…' : file ? `${(file.size/1024).toFixed(0)} KB · choose another file` : 'Click here to select a file'}</span><small>PDF OR TXT <i/> MAX 10 MB</small>
            </div>
            {error && <div className="alert"><X size={15}/>{error}</div>}
            <div className="upload-footer"><span><span className="lock">◈</span> Files are not saved on the server</span><button className="button primary" disabled={busy} onClick={() => runAnalysis()}>{busy ? <><LoaderCircle className="spin" size={16}/> Analyzing…</> : <>Analyze file <ArrowRight size={16}/></>}</button></div>
            <div className="demo-line"><Sparkles size={15}/><span>No file?</span><button onClick={() => runAnalysis(new File([sampleText], 'introduction-to-ai.txt', { type: 'text/plain' }))}>Use sample notes <ArrowRight size={14}/></button></div>
          </div>
          <aside className="aside-card"><span className="overline">HOW IT WORKS</span><h3>Upload. Review. Practice.</h3><p>Your file becomes a summary, key topics and a quiz. OpenRouter's free model router is limited to 50 requests per day.</p><div className="mini-flow"><span><FileText size={16}/> Select your file</span><i/><span><Brain size={16}/> Review topics</span><i/><span><Target size={16}/> Take a quiz</span></div><div className="privacy-note"><span className="status-dot"/> OpenRouter key stays in local backend settings</div></aside>
        </div>
        {analysis && <button className="recent-card" onClick={() => setPage('analysis')}><span className="recent-icon"><FileText size={18}/></span><span><small>LAST ANALYSIS</small><b>{analysis.document_name}</b></span><span className="recent-count">{analysis.topics.length} topics · {analysis.mcqs.length} questions</span><ArrowRight size={16}/></button>}
      </section>}

      {page === 'analysis' && analysis && <section className="page-pad"><button className="back-link" onClick={() => setPage('dashboard')}><ArrowLeft size={15}/> Workspace</button><div className="page-title-row analysis-title"><div><div className="eyebrow">MATERIAL ANALYSIS <span className="mode-tag">{analysis.mode === 'ai' ? 'AI GENERATED' : 'SOURCE MODE'}</span></div><h1 className="page-title">{analysis.document_name}</h1><p className="muted">{analysis.character_count.toLocaleString()} characters · {analysis.notice}</p></div><button className="button secondary" onClick={startQuiz}><Target size={16}/> Start quiz <ArrowRight size={15}/></button></div>{analysis.mode !== 'ai' && <div className="demo-notice"><Sparkles size={17}/><span><b>Source-based study mode</b>{analysis.notice}</span></div>}<div className="analysis-grid"><div className="content-card summary-card"><div className="card-heading"><span className="feature-icon hue-0"><Sparkles size={17}/></span><div><span className="overline">THE BIG PICTURE</span><h2>Quick summary</h2></div></div><p className="summary-short">{analysis.summary_short}</p><details><summary>Read the detailed summary <ChevronDown size={15}/></summary><p>{analysis.summary_detailed}</p></details><div className="keypoints"><span className="overline">KEY POINTS</span>{analysis.key_points.map((p,i)=><div className="keypoint" key={i}><Check size={15}/><span>{p}</span></div>)}</div></div><div className="content-card topic-card"><div className="card-heading"><span className="feature-icon hue-1"><Brain size={17}/></span><div><span className="overline">WHAT MATTERS MOST</span><h2>Key topics <span className="count-badge">{analysis.topics.length}</span></h2></div></div><div className="topic-list">{analysis.topics.map((t,i)=><div className="topic-row" key={i}><div><b>{t.name}</b><p>{t.explanation}</p></div><span className={`importance ${(t.importance||'medium').toLowerCase()}`}>{t.importance}</span></div>)}</div></div></div><div className="analysis-bottom"><div className="content-card question-preview"><span className="overline">READY TO PRACTICE?</span><h2>{analysis.mcqs.length} questions, built from your material.</h2><p>See what stuck and get a focused recommendation for what to review next.</p><button className="button primary" onClick={startQuiz}>Start a quick quiz <ArrowRight size={15}/></button></div><div className="content-card study-preview"><span className="overline">OPEN ENDED PRACTICE</span><h2>{analysis.questions.length} study questions</h2><p>Short answer, conceptual and exam style prompts—with answers to check your understanding.</p><button className="button text-button" onClick={() => setPage('questions')}>Browse study questions <ArrowRight size={15}/></button></div></div></section>}

      {page === 'questions' && analysis && <section className="page-pad"><button className="back-link" onClick={() => setPage('analysis')}><ArrowLeft size={15}/> Back to analysis</button><div className="eyebrow">A LITTLE MORE DEPTH</div><h1 className="page-title">Study questions</h1><p className="muted questions-intro">Think through the answer before expanding the card. Questions come from {analysis.document_name}.</p><div className="question-list">{analysis.questions.map((q,i)=><article className="content-card question-card" key={i}><button className="question-toggle" onClick={() => setExpanded(expanded===i?-1:i)}><span className="q-number">{String(i+1).padStart(2,'0')}</span><span className="q-body"><span className="q-tags"><i className={`difficulty ${(q.difficulty||'easy').toLowerCase()}`}>{q.difficulty}</i><i>{q.topic}</i></span><b>{q.question}</b></span>{expanded===i?<ChevronUp size={18}/>:<ChevronDown size={18}/>}</button>{expanded===i&&<div className="answer-body"><div><small>EXPECTED ANSWER</small><p>{q.expected_answer}</p></div><div><small>WHY IT MATTERS</small><p>{q.explanation}</p></div></div>}</article>)}</div></section>}

      {page === 'quiz' && analysis && <section className="quiz-wrap"><button className="back-link" onClick={() => setPage('analysis')}><ArrowLeft size={15}/> Back to analysis</button><div className="quiz-kicker"><span className="eyebrow">QUIZ</span><span>Question {index+1} <i>/</i> {analysis.mcqs.length}</span></div><div className="progress-track"><span style={{width:`${(index+1)/analysis.mcqs.length*100}%`}}/></div><article className="quiz-card"><div className="quiz-meta"><span className={`difficulty ${(analysis.mcqs[index].difficulty||'easy').toLowerCase()}`}>{analysis.mcqs[index].difficulty}</span><span>{analysis.mcqs[index].topic}</span></div><h1>{analysis.mcqs[index].question}</h1><div className="options">{analysis.mcqs[index].options.map((option,i)=><button key={i} type="button" className={`option ${answers[index]===i?'selected':''}`} aria-pressed={answers[index]===i} onClick={() => setAnswers({...answers,[index]:i})}><span className="option-letter">{String.fromCharCode(65+i)}</span><span>{option}</span>{answers[index]===i&&<Check size={17}/>}</button>)}</div></article>{error&&<div className="alert">{error}</div>}<div className="quiz-footer"><button className="button secondary" disabled={index===0} onClick={()=>setIndex(Math.max(0,index-1))}><ArrowLeft size={15}/> Previous</button><span>{Object.keys(answers).length} of {analysis.mcqs.length} answered</span><span className="quiz-actions">{index<analysis.mcqs.length-1&&<button className="button secondary" onClick={()=>setIndex(index+1)}>Next <ArrowRight size={15}/></button>}<button className="button primary" disabled={busy} onClick={submitQuiz}>{busy?<><LoaderCircle className="spin" size={16}/> Checking…</>:'Submit quiz'} <Check size={16}/></button></span></div></section>}

      {page === 'results' && result && <section className="page-pad"><div className="result-head"><span className="eyebrow">SESSION COMPLETE</span><h1 className="page-title">Look how far you’ve come.</h1><p className="muted">A little reflection makes the next study session count.</p></div><div className="result-overview"><div className="score-card"><div className="score-ring" style={{'--score':`${result.percentage}%`}}><div><b>{result.percentage}<small>%</small></b><span>SCORE</span></div></div><span className="score-label">{result.performance}</span><p>Every question is another chance to learn.</p></div><div className="result-metrics"><div className="metric-card"><span className="metric-icon green"><Check size={17}/></span><small>CORRECT</small><b>{result.correct}<i> / {result.total}</i></b></div><div className="metric-card"><span className="metric-icon rose"><X size={17}/></span><small>TO REVISIT</small><b>{result.incorrect}<i> / {result.total}</i></b></div><div className="metric-card"><span className="metric-icon violet"><Brain size={17}/></span><small>TOPICS IN THIS QUIZ</small><b>{analysis.topics.length}<i> concepts</i></b></div></div></div><div className="results-grid"><article className="content-card feedback-card"><div className="card-heading"><span className="feature-icon hue-0"><Sparkles size={17}/></span><div><span className="overline">A NOTE FOR YOU</span><h2>Performance reflection <i className="mode-tag">{result.mode === 'ai' ? 'AI' : 'RULE BASED'}</i></h2></div></div><p>{result.feedback}</p><div className="recommendations"><span className="overline">YOUR NEXT STUDY STEPS</span>{result.recommendations.map((r,i)=><div key={i}><span>{String(i+1).padStart(2,'0')}</span>{r}</div>)}</div></article><article className="content-card weak-card"><div className="card-heading"><span className="feature-icon hue-2"><Target size={17}/></span><div><span className="overline">FOCUS YOUR REVIEW</span><h2>Topics to revisit</h2></div></div>{result.weak_topics.length?result.weak_topics.map((t,i)=><div className="weak-row" key={i}><span className="weak-number">0{i+1}</span><b>{t.name}</b><span className={`importance ${t.priority.toLowerCase()}`}>{t.priority} priority</span></div>):<div className="all-good"><Check size={18}/> Nothing missed this time. Keep it up!</div>}</article></div><div className="result-actions"><button className="button secondary" onClick={startQuiz}><RotateCcw size={16}/> Retake quiz</button><button className="button primary" onClick={reset}>Back to workspace <ArrowRight size={16}/></button></div></section>}
    </main>
  </div>
}
